apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ include "control-plane-kubeadm.metadata.name" . }}
  namespace: {{ include "control-plane-kubeadm.metadata.namespace" . }}
  labels: {{- include "control-plane-kubeadm.metadata.labels" . | nindent 4 }}
spec:
  version: {{ .Values.kubernetesVersion | default .Values.global.kubernetesVersion }}
  replicas: {{ .Values.replicas }}
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
          - localhost
          - 127.0.0.1
          - 0.0.0.0
  machineTemplate:
    infrastructureRef:
      apiVersion: {{ .Values.machineTemplate.infrastructureRef.apiVersion }}
      kind: {{ .Values.machineTemplate.infrastructureRef.kind }}
      name: {{ .Values.machineTemplate.infrastructureRef.name | default (include "control-plane-kubeadm.metadata.template-name" . ) }}
      namespace: {{ .Values.machineTemplate.infrastructureRef.name | default (include "control-plane-kubeadm.metadata.namespace" . ) }}
